### ISSUE TITLE
Django 5.0 support

### ISSUE THREAD

**Issue by nijel** [mfogel/django-timezone-field#112]
`pip install Django==5.0a1 django-timezone-field==6.0.1` fails with:

`django-timezone-field 6.0.1 requires Django<5.0,>=3.2, but you have django 5.0a1 which is incompatible.`

See https://docs.djangoproject.com/en/dev/releases/5.0/ for release notes.

**Comment by mfogel** [comment]
Support for installing alongside django 5.0 has been merged to `main`!

**Comment by hugorodgerbrown** [comment]
@mfogel is there a timeline for the next release (with 5.0 support)?

**Comment by mfogel** [comment]
@hugorodgerbrown released django 5.0 support to pypi just now. Let me know if you run into any issues, cheers.

**Comment by hugorodgerbrown** [comment]
Thanks, will test tomorrow.
