### ISSUE TITLE
Using the "Factory" timezone on systems that use the system zoneinfo database can cause problems

### ISSUE THREAD

**Issue by knobix** [mfogel/django-timezone-field#114]
On some systems, e.g. FreeBSD, if the system installied zoneinfo database is used this can lead to `ValueError` exceptions if using the `Factory` timezone.

The affected line is: [https://github.com/mfogel/django-timezone-field/blob/main/timezone_field/backends/zoneinfo.py#L21](https://github.com/mfogel/django-timezone-field/blob/main/timezone_field/backends/zoneinfo.py#L21)

Here's a way to reproduce the issue:

```
import zoneinfo

print("Current TZPATH: {}".format(zoneinfo.TZPATH))
try:
    print("ZoneInfo: {}".format(zoneinfo.ZoneInfo('Factory')))
except Exception as error:
    print("An error occurred: {}".format(error))
    pass
```

Output:
```
Current TZPATH: ('/usr/share/zoneinfo', '/usr/lib/zoneinfo', '/usr/share/lib/zoneinfo', '/etc/zoneinfo')
An error occurred: Invalid STD format in b'<Local time zone must be set--use tzsetup>0'`
```

If using the `tzdata` package the problem doesn't occur:

```
import zoneinfo

zoneinfo.reset_tzpath(["/usr/local/lib/python3.9/site-packages/tzdata/zoneinfo/"])
print("Current TZPATH: {}".format(zoneinfo.TZPATH))
print("ZoneInfo: {}".format(zoneinfo.ZoneInfo('Factory')))
```

Output:

```
Current TZPATH: ('/usr/local/lib/python3.9/site-packages/tzdata/zoneinfo/',)
ZoneInfo: Factory
```

The described behavior was observed on FreeBSD 12.4-RELEASE, 13.2-RELEASE and 14.0-BETA4 with Python 3.9.18.

**Comment by mfogel** [comment]
Thanks for the bug report and fix @knobix ! Merged.
