### ISSUE TITLE
Does not support Django5 - This blocks upgrades

### ISSUE THREAD

**Issue by duaneking** [mfogel/django-timezone-field#120]
This lack of support for Django 5 is blocking upgrades.

**Comment by mfogel** [comment]
hum, I'm confused. The latest release should support django 5.0. As far as I know django 5.0 is included in all the [right](https://github.com/mfogel/django-timezone-field/blob/034996f90fdbba4e51878c959ef59b4cc381b35d/pyproject.toml#L31) [places](https://github.com/mfogel/django-timezone-field/blob/034996f90fdbba4e51878c959ef59b4cc381b35d/pyproject.toml#L41) in pyproject.toml... and [pypi](https://pypi.org/project/django-timezone-field/) seems to think it django 5.0 is supported. 

What issue exactly are you running into? Maybe something got missed?

**Comment by tuky** [comment]
Yes, should be fine. It might be another library that is using this one here. e.g. `django-bootstrap-datepicker-plus`still depends on django < 5

**Comment by cclauss** [comment]
For me, the downgrade was caused by celery/django-celery-beat#698

**Comment by duaneking** [comment]
It looks like somebody on your side did a silent update; the package seems to work now. Before, attempts to do so got an error saying the package did not support django5.

If you get this error, I suggest you update this package first, then update Django to 5 as pip might complain otherwise.

**Comment by cclauss** [comment]
I think this can be closed.

(.venv) ➜ `dj5-hack python -m pip install django-timezone-field==6.1.0`
(.venv) ➜ `dj5-hack python -m pipdeptree`
```
django-timezone-field==6.1.0
└── Django [required: >=3.2,<6.0, installed: 5.0]
    ├── asgiref [required: >=3.7.0, installed: 3.7.2]
    └── sqlparse [required: >=0.3.1, installed: 0.4.4]
```
---
> It might be another library that is using this one here. e.g. django-bootstrap-datepicker-plus

@tuky `django-bootstrap-datepicker-plus` has Dj5 issues but it does not depend on `django-timezone-field`
(.venv) ➜  `pip install django-bootstrap-datepicker-plus==5.0.4`
(.venv) ➜  `dj5-hack python -m pipdeptree`
```
django-bootstrap-datepicker-plus==5.0.4
├── Django [required: >=2,<5, installed: 4.2.8]
│   ├── asgiref [required: >=3.6.0,<4, installed: 3.7.2]
│   └── sqlparse [required: >=0.3.1, installed: 0.4.4]
├── pydantic [required: Any, installed: 2.5.2]
│   ├── annotated-types [required: >=0.4.0, installed: 0.6.0]
│   ├── pydantic-core [required: ==2.14.5, installed: 2.14.5]
│   │   └── typing-extensions [required: >=4.6.0,!=4.7.0, installed: 4.8.0]
│   └── typing-extensions [required: >=4.6.1, installed: 4.8.0]
└── typing-extensions [required: Any, installed: 4.8.0]
```
