### ISSUE TITLE
How to convert timezone name to Coordinated Universal Time (UTC)

### ISSUE THREAD

**Issue by huynd26** [mfogel/django-timezone-field#127]
My instance have a timezone field with the value is `zoneinfo.ZoneInfo(key='Europe/Paris')` , so I want to convert it to UTC+2, How do I do it ? Thanks so much !!!

**Comment by mfogel** [comment]
hi @huynd26 , [stackoverflow](https://stackoverflow.com/search?q=zoneinfo+convert+timezone) would be a better place to ask this question than github.
