### ISSUE TITLE
TimeZoneSerializerField should allow empty strings when required=False

### ISSUE THREAD

**Issue by ejain** [mfogel/django-timezone-field#130]

**Comment by paulocoutinhox** [comment]
do you have a sample code to i understand?

**Comment by mfogel** [comment]
This isn't quite what `required=True` does - this allows the field to be omitted altogether - which is different then specifying the field as the empty string (or as `None`). This is documented [here](https://www.django-rest-framework.org/community/3.0-announcement/#the-required-allow_null-allow_blank-and-default-arguments)

Once #137 is merged, you can use the `allow_blank=True` kwarg to allow empty strings if you so desire.

**Comment by ejain** [comment]
@mfogel Perfect, thanks!
