### ISSUE TITLE
shouldn't TimeZoneFormField and TimeZoneFieldBase choices init be the same ?

### ISSUE THREAD

**Issue by shostelet** [mfogel/django-timezone-field#20]
TimeZoneFieldBase choices is based on ```pytz.common_timezones``` while TimeZoneFormField is based on ```pytz.all_timezones```
Shouldn't they be based on the same initial list of choices ? In case you create a form with TimeZoneFormField, you offer choices to the user that are not, by default, compatible with TimeZoneFieldBase validator.

**Comment by mfogel** [comment]
Good point, I'll look into adjusting it.
