### ISSUE TITLE
null=True should be enforced

### ISSUE THREAD

**Issue by atleta** [mfogel/django-timezone-field#23]
Hi,

Though the comments in the code state that the empty value is '' (the empty string) even if the field is set to None (null), this is not true. The opposite is true: the empty value is always encoded as None. (See lines 86-87.)

However, by default the field (as the underlying CharField) has null=False and it will break things as soon as one adds an empty field. (E.g. right when running the migration.)

**Comment by mfogel** [comment]
Thanks for the ticket. That's a pretty serious failure... I've pushed a fix to the develop branch https://github.com/mfogel/django-timezone-field/commit/ffe790a8bc5c376aeed44a2e2e7192b604dcd15c can you try that out and see if it fixes the issue for you? If so I can push a new release out to pypi with that fix in there.

**Comment by mfogel** [comment]
This fix is on develop and will be included in the next release.
