### ISSUE TITLE
Timezone field value always displays as (None) in admin list view

### ISSUE THREAD

**Issue by saxbophone** [mfogel/django-timezone-field#26]
Hi,

When I use this field in a model and set the field to be displayed in the django admin list view, no matter what the value of the field is for any record the value is always displayed as `(None)`. The field is displayed correctly in the edit view for individual records. I tried to create a workaround and I could get the field to display in the list view by creating a method in the model that returns that field, however it feels like this should be done automatically. This is in Django 1.8 with Django Suit theme.

**Comment by mfogel** [comment]
I've replicated this behavior on django 1.7 as well.

**Comment by mfogel** [comment]
What's going on here is the django admin is expecting the first argument of the `choices` list to be of the same type as the value returned by the field. Right now the first argument of the `choices` list is a string describing a pytz timezone, while the value returned by this field is actually a pytz timezone.

Probably need to specify or at least store `choices` as (<pytz timezone>, <stirng>).

**Comment by saxbophone** [comment]
Thanks for looking into this @mfogel 

Aha that makes sense. I wonder if there is any way to explicitly tell django what value to use to represent a field for its admin views (like maybe a method that needs to be overridden in the field's class definition or something similar)?

**Comment by mfogel** [comment]
This is fixed in the 1.3 release I just pushed to pypi a few minutes ago. Give it a try, let me know if it doesn't work for you.

**Comment by saxbophone** [comment]
@mfogel Thanks! I will definitely try it out in the next few hours and let you know if it works :smiley:

**Comment by saxbophone** [comment]
@mfogel That did the trick :smile: thanks a bunch :+1:
