### ISSUE TITLE
Incorrect null=False behavior

### ISSUE THREAD

**Issue by hwkns** [mfogel/django-timezone-field#28]
Because of the change in https://github.com/mfogel/django-timezone-field/commit/71f107e1ceb491b685033e5a538d24d6c7b50a1b, you can set a `TimeZoneField` to `None` and save the model without raising an `IntegrityError`.  This is because `get_prep_value()` returns the empty string (`''`).

This behavior is inconsistent with other `null=False` fields, and there is no longer any way for me to enforce that my model must have a time zone.

**Comment by mfogel** [comment]
To enforce that the model must have a time zone - what if you set `blank=False` on the field ?

**Comment by hwkns** [comment]
I have set `blank=False`.  That only applies to forms, so any API interactions can still create an object without a timezone.

**Comment by mfogel** [comment]
Could you call `model.full_clean()` or `model.clean_fields()` ?

As you probably saw, this is based on the CharField... as such given the choice of how to save empty values to the DB - the choice is either to use the empty string or to actually save a null value. I'd rather go with the default behavior for the CharField, which is to use the empty string.

**Comment by hwkns** [comment]
That might make sense if `TimeZoneField` was basically a `CharField` with custom choices and validation, but no -- `to_python()` does not return a string, it returns a timezone object.  If there is no timezone, the python representation of the field should be `None`.

The default behavior of `CharField` is *not* to represent `None` as the empty string.  The default behavior, if you set `null=False` and try to set the value to `None`, is an `IntegrityError`.

**Comment by mfogel** [comment]
I'd use the model `clean()` methods to do validation rather than rely on my DB to throw integrity errors... that's what they're there for.

In any case, you're welcome to fork the project and change the implementation around so that those integrity errors are thrown in the right spots for you.

**Comment by diwu1989** [comment]
I don't get why this library has to go against the normal convention in Django form fields.
My organization is also not able to use your latest code for the exact same reason that @hwkns brought up.

**Comment by thinkt4nk** [comment]
this is ridiculous
