### ISSUE TITLE
Setting value to None with null=True results in validation error on model.full_clean

### ISSUE THREAD

**Issue by richardhills** [mfogel/django-timezone-field#31]
The TimeZoneFieldBase.validate method doesn't accept None as a value when null=True.

**Comment by mfogel** [comment]
To get the `validate()` method to accept `None` as a legit value, you can use the `blank` kwarg. The `null` kwarg [does not affect python-level validation](https://docs.djangoproject.com/en/1.11/ref/models/fields/#null).

Cheers
