### ISSUE TITLE
Why timezone name displayed with underscore? 

### ISSUE THREAD

**Issue by mr-linch** [mfogel/django-timezone-field#32]
Hello. 

For example: timezone **America/Los Angeles** displayed as **America/Los_Angeles**. How I can change this behavior?

Thanks.

**Comment by mfogel** [comment]
Thanks for bringing it up, the default will be changed as you suggest in the next major version.

**Comment by mfogel** [comment]
The default human-readable values have been changed to have spaces instead of underscores, as you suggest. Thanks for brining it up!

This change will be included in the next release.
