### ISSUE TITLE
Unable to set field label

### ISSUE THREAD

**Issue by inoks** [mfogel/django-timezone-field#42]
`TimeZoneField` currently does not accept custom label, either via first positioning argument:

```
tz = TimeZoneField('Custom Time Zone', null=True, blank=True)
```
> ValueError: need more than 1 value to unpack

**Comment by mfogel** [comment]
@inoks thanks for the bug report. Does django support setting the `label` of a form field via a positional argument? I don't see that mentioned in the docs [here](https://docs.djangoproject.com/en/1.11/ref/forms/fields/#label)... am I missing it or do you know where that's mentioned somewhere else?

I think it'll work if you make label a keyword argument.

`tz = TimeZoneField(label='Custom Time Zone', null=True, blank=True)`

Cheers

**Comment by kevin-brown** [comment]
Django supports setting the verbose name on a model field using positional arguments.

[Django Timezone Field](https://github.com/mfogel/django-timezone-field/blob/de8976016c53671f486059d6819df974df373ed1/timezone_field/fields.py#L42) has a nonstandard set of positional arguments when compared to the [standard Django model field class](https://github.com/django/django/blob/4554f9a783665d64b59c35b53ae71178e56ac783/django/db/models/fields/__init__.py#L134-L140).

[Other Django fields](https://github.com/django-extensions/django-extensions/blob/3410f6a819a2ac9373d0387ca62c3255260a5e18/django_extensions/db/fields/__init__.py#L101-L103) get around this by not supporting positional arguments for their custom arguments.

**Comment by mfogel** [comment]
@kevin-brown thanks for the pointers, I've added a commit (linked above) that allows for a few positional args to be used. Let me know if you have any thoughts.
