### ISSUE TITLE
Ability to have offsets in form field

### ISSUE THREAD

**Issue by stalker314314** [mfogel/django-timezone-field#46]
Hi,
Besides just showing drop-down box with names of timezones, it would be nice to show them with offsets, in parenthesis maybe. It is usual practice on a lot of websites (example is from crowdin, but I think you are aware of what I am referring to)

![slika](https://user-images.githubusercontent.com/188751/39410912-dceac272-4bff-11e8-9a4e-ee032374ed79.png)

Maybe not as default behavior, but controllable over settings (not sure, just throwing ideas)

**Comment by mfogel** [comment]
Yeah, looks like a good idea. Pull requests happily entertained :) I would prefer this was first implemented as optional behavior, not default. If it's great and everyone loves it, we can later move it from optional to default.

**Comment by bernd-wechner** [comment]
Great idea but yes indeed should always be optional IMHO.

**Comment by mfogel** [comment]
This was merged into master in 6b8bbc41d0bbbcaba27bab8ec2ebe610cca464a9 and will be included in the next release.

**Comment by drtpotter** [comment]
This feature doesn't appear to be in 4.0, would be great to see it there!

**Comment by mfogel** [comment]
@drtpotter it's available as an optional kwarg for the field, `choices_display='WITH_GMT_OFFSET'`. There's an example available of using this kwarg in the README.
