### ISSUE TITLE
Error when accessing changed_data in a ModelForm that uses TimeZoneFormField

### ISSUE THREAD

**Issue by Pepedou** [mfogel/django-timezone-field#47]
I added `TimeZoneField` to my User Profile Model.
I added `TimeZoneFormField` to a simple `Form`.

I instantiated the form passing the user's timezone as part of the `initial` dictionary.

`form = SettingsForm(initial={'language': user.language, 'email': user.email, 'timezone': user.timezone})`

In one of the form's `clean_field` methods, I access `self.changed_data` and an exception is raised because it's assuming that 'timezone' is a string and it's trying to uppercase it.

`'America/Mexico_City' object has no attribute 'upper'`.

The exception is thrown at this line:
`if zone.upper() == 'UTC':`
`python3.6/site-packages/pytz/__init__.py in timezone, line 162`

Here is the form:

```
class SettingsForm(Form):
    language = forms.ChoiceField(choices=settings.LANGUAGES)
    email = forms.EmailField()
    timezone = timezone_field.TimeZoneFormField()

    def clean_email(self):
        email = self.cleaned_data.get('email')

        if 'email' not in self.changed_data: # The exception is thrown when accessing changed_data
            return email

        if AuthUser.objects.filter(email=email).exists():
            raise ValidationError(_('That email already exists.'), code='email_exists')

        return email
```

**Comment by Pepedou** [comment]
If in `initial` I use `{'timezone': user.timezone.zone}` the problem is fixed.

**Comment by mfogel** [comment]
Hi @Pepedou - yeah, as you figured out the form is expecting the values of `initial` to be strings, not timezone objects.
