### ISSUE TITLE
Deconstruct in makemigrations

### ISSUE THREAD

**Issue by iamit** [mfogel/django-timezone-field#48]
I have my own addon on makemigrations, I think it is quite rediculous that django migrations react to language differences in field arguments like 'verbose_name', 'help_text', 'related_name or  'choices'

so i override the makemigations.py by:

    IGNORED_ATTRS = ['verbose_name', 'help_text', 'related_name', 'choices']
    original_deconstruct = models.Field.deconstruct

    def new_deconstruct(self):
        name, path, args, kwargs = original_deconstruct(self)
        for attr in IGNORED_ATTRS:
            kwargs.pop(attr, None)
        return name, path, args, kwargs
    
    models.Field.deconstruct = new_deconstruct

This works well for all packages, except for this one (django-timezone-field), there i got:

an error on the fields.py line 79 (version 3.0 for python 2.7)

    def deconstruct(self):
        name, path, args, kwargs = super(TimeZoneField, self).deconstruct()
        if kwargs['choices'] == self.CHOICES:
            del kwargs['choices']

so is it possible for you to change the code, and first check if the key is in the kwargs?, like for example:

    if 'choices'in kwargs and kwargs['choices'] == self.CHOICES:

the same for the line below (max_length), not needed for me, but just in case....

**Comment by iamit** [comment]
By the way, is solved this in my code by doing this (but to make an excpetion just for this package feels kind of weird:

`IGNORED_ATTRS = ['verbose_name', 'help_text', 'related_name', 'choices']

original_deconstruct = models.Field.deconstruct

def new_deconstruct(self):
    if self.__class__.__name__ == 'TimeZoneField' and self.__class__.__module__ == 'timezone_field.fields':
        ignored_attrs = ['verbose_name', 'help_text', 'related_name']
    else:
        ignored_attrs = IGNORED_ATTRS
    name, path, args, kwargs = original_deconstruct(self)
    for attr in ignored_attrs:
        kwargs.pop(attr, None)
    return name, path, args, kwargs

models.Field.deconstruct = new_deconstruct`

**Comment by mfogel** [comment]
@iamit 8ace084 adds support for this to `master`, it'll be included in the next release. Hope it works - let me know if not. Cheers.
