### ISSUE TITLE
[feature request] `verbase_name` support

### ISSUE THREAD

**Issue by Eraldo** [mfogel/django-timezone-field#51]
I am a big fan of consistency and currently all my model fields have an explicit translated `verbase_name` property.

Example:
```python
    timezone = TimeZoneField(
        verbase_name=_('timezone'),
        default=pytz.UTC,
    )
```

However this currently does not work for `TimeZoneField`. :|
I get this Error: `__init__() got an unexpected keyword argument 'verbase_name'`

How about adding support for it? :)

**Comment by Abnormally** [comment]
Maybe try `verbose_name` instead?)

**Comment by Eraldo** [comment]
I feel a bit ashamed of myself for not only not having spotted it in the first place, but also not having noticed when creating this issue (most copy pasting *cough*).

Thank you for the clarification!
And thanks for the package in the first place. *bow*
