### ISSUE TITLE
Object of type 'Europe/Amsterdam' is not JSON serializable

### ISSUE THREAD

**Issue by mvdwaeter** [mfogel/django-timezone-field#55]
Using: 
```
Django==2.2.6
djangorestframework==3.10.3
django-timezone-field==3.1
```

Having a simple Django model with a TimeZonefield:

```
from timezone_field import TimeZoneField

class Event(models.Model):
    event_tz = TimeZoneField(default=settings.TIME_ZONE)
```

and a simple DRF modelserializer:
```
class EventSerializer(serializers.ModelSerializer):

    class Meta:
        model = Event
        fields = (
            'id',
        )
```
Note that I don't event display the `event_tz` field.
I get the error: `Object of type 'Europe/Amsterdam' is not JSON serializable` when I display a detail page with this serializer.

Any idea what could have caused this?

**Comment by mvdwaeter** [comment]
(╯°□°)╯︵ ┻━┻ 

Turns out I was looking at the EventSerializer, but I should have looked at the UpdateEventSerializer, as DRF displays an update form under the detail view when using a BrowsableAPIRenderer.
Simply using the correct serializer field was enough.

**Comment by hellorahulnarang** [comment]
How did you solve this error
