### ISSUE TITLE
When saving timezone field with string value it won't get converted to pytz object

### ISSUE THREAD

**Issue by imomaliev** [mfogel/django-timezone-field#57]
```
obj = MyModel.objects.create(timezone='Europe/Berlin')
assert not isinstance(obj.timezone, str)
```

It should return pytz object. I'm not sure but we probably will have to create descriptor like `FileField` has

**Comment by mfogel** [comment]
Agreed this would be better to return a timezone object. Pull requests happily entertained.

**Comment by mfogel** [comment]
The fix for this is on `main` and will be included in the next release to pypi, which will be a major version bump.
