### ISSUE TITLE
Django 3.0 support

### ISSUE THREAD

**Issue by farid-fari** [mfogel/django-timezone-field#59]
It seems that this package causes a crash with Django 3.0

Upon running the `runserver` command, I get:

    File "/donnees/virtualenvs/django/lib/python3.8/site-packages/timezone_field/fields.py", line 5, in <module>
        from django.utils import six
    ImportError: cannot import name 'six' from 'django.utils'

**Comment by jyr** [comment]
I have the same error and researching I found an issue about that.

https://github.com/jazzband/django-silk/issues/377

Maybe this cal help us to resolve it:

https://octolinker-demo.now.sh/sebleier/django-redis-cache/pull/174/files#diff-8138f91c2fdb7407f749c37d0c0ef4bdL5

**Comment by acerix** [comment]
`six` provides Python 2/3 compatibility and was removed in Django 3 so many packages have this issue.

https://docs.djangoproject.com/en/dev/releases/3.0/#removed-private-python-2-compatibility-apis

I suggest replacing the `six` references with native Python 3 which means dropping support for Python 2. Another option is to drop in [six](https://pypi.org/project/six/).

**Comment by mfogel** [comment]
I pushed a new version with django 3.0 support to pypi a few minutes ago, this should now work with the new version. If not, please re-open or file a new bug. cheers!
