### ISSUE TITLE
fields.py __init__ missing choices_display argument?

### ISSUE THREAD

**Issue by linhnvhicts** [mfogel/django-timezone-field#66]
Hello i tried to add `choices_display` to TimezoneField() but seems like it doesn't accept that argument:

```
from timezone_field import TimeZoneField

timezone = TimeZoneField(default='Asia/Saigon', choices_display='WITH_GMT_OFFSET')
```

my environment: 

- MacOS

- python3.8

- django-timezone-field version: django-timezone-field = "^4.0"

Full error traceback:

> Watching for file changes with StatReloader
> Exception in thread django-main-thread:
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
>     self.run()
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
>     self._target(*self._args, **self._kwargs)
>   File "/Users/admin/Library/Caches/pypoetry/virtualenvs/base.django-AnqsdXoZ-py3.8/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
>     fn(*args, **kwargs)
>   File "/Users/admin/Library/Caches/pypoetry/virtualenvs/base.django-AnqsdXoZ-py3.8/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 110, in inner_run
>     autoreload.raise_last_exception()
>   File "/Users/admin/Library/Caches/pypoetry/virtualenvs/base.django-AnqsdXoZ-py3.8/lib/python3.8/site-packages/django/utils/autoreload.py", line 76, in raise_last_exception
>     raise _exception[1]
>   File "/Users/admin/Library/Caches/pypoetry/virtualenvs/base.django-AnqsdXoZ-py3.8/lib/python3.8/site-packages/django/core/management/__init__.py", line 357, in execute
>     autoreload.check_errors(django.setup)()
>   File "/Users/admin/Library/Caches/pypoetry/virtualenvs/base.django-AnqsdXoZ-py3.8/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
>     fn(*args, **kwargs)
>   File "/Users/admin/Library/Caches/pypoetry/virtualenvs/base.django-AnqsdXoZ-py3.8/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "/Users/admin/Library/Caches/pypoetry/virtualenvs/base.django-AnqsdXoZ-py3.8/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
>     app_config.import_models()
>   File "/Users/admin/Library/Caches/pypoetry/virtualenvs/base.django-AnqsdXoZ-py3.8/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
>     self.models_module = import_module(models_module_name)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/Users/admin/Documents/git/icts/vietphil.hoola/backend/models/__init__.py", line 1, in <module>
>     from .user import User
>   File "/Users/admin/Documents/git/icts/vietphil.hoola/backend/models/user.py", line 7, in <module>
>     class User(AbstractUser):
>   File "/Users/admin/Documents/git/icts/vietphil.hoola/backend/models/user.py", line 29, in User
>     timezone = TimeZoneField(default='Asia/Saigon', choices_display='WITH_GMT_OFFSET')
>   File "/Users/admin/Library/Caches/pypoetry/virtualenvs/base.django-AnqsdXoZ-py3.8/lib/python3.8/site-packages/timezone_field/fields.py", line 74, in __init__
>     super(TimeZoneField, self).__init__(*args, **kwargs)
> TypeError: __init__() got an unexpected keyword argument 'choices_display'

I read over https://github.com/mfogel/django-timezone-field/blob/master/timezone_field/fields.py#L43 and seems like it's correct because you using `kwargs`. Do you know why extra argument caused the error?

**Comment by mfogel** [comment]
Hi @linhnvhicts thanks for the ticket

The `choices_display` kwarg is brand-new so it hasn't been pushed to pypi yet. It's only available if you installed this package directly from github. Do you know how you installed the package?

I'm planning to release a new version to pypi this upcoming weekend, baring any show-stopper bug reports.

**Comment by linhnvhicts** [comment]
@mfogel hello thank for quick response, i installed it with `poetry add django-timezone-field` because i used poetry as my env, i think it's the same as `pip install django-timezone-field` 
Here is my pyproject.tonml with it:
```
[tool.poetry.dependencies]
python = "^3.8"
celery = "^5.0.2"
django-filter = "^2.4.0"
djangorestframework = "^3.12.2"
gunicorn = "^20.0.4"
psycopg2-binary = "^2.8.6"
Django = "^3.1.3"
django-timezone-field = "^4.0"
```

**Comment by mfogel** [comment]
Ok, that looks good - that will install the published version from pypi. To get the version from github it should work to run

```
poetry remove django-timezone-field
poetry add git+https://github.com/mfogel/django-timezeon-field.git
```

Once I push a new version to pypi (planned for this weekend) you can switch back to installing from pypi.
