### ISSUE TITLE
django timezone field seems to *always* require django-rest-framework

### ISSUE THREAD

**Issue by 2ps** [mfogel/django-timezone-field#67]
the timezone field has an import from `rest_framework` so this should be an always-required installation and not just an `extras` require.

**Comment by mfogel** [comment]
Thanks for the heads up

I will adjust and push a fix to pypi shortly

**Comment by mfogel** [comment]
`v4.1.1` has been pushed to pypi which should fix this problem. `rest_framework` isn't imported in the package root anymore. Sorry about that oversight

Please try it out when you get a chance and if it's still not working let me know
