### ISSUE TITLE
How to set Default Timezone in the form

### ISSUE THREAD

**Issue by estaar** [mfogel/django-timezone-field#73]
How do you set default timezone to the form which I have done like this:

timezone = TimeZoneFormField(choices_display='WITH_GMT_OFFSET', default='UTC', required=True)

I get this error>
TypeError: __init__() got an unexpected keyword argument 'default'

**Comment by mfogel** [comment]
Hey @estaar, thanks for your question, I think this stackoverflow may help you out https://stackoverflow.com/questions/604266/django-set-default-form-values
