### ISSUE TITLE
DRF TimezoneField not rendering correctly to the openapi spec with SchemaView

### ISSUE THREAD

**Issue by gabn88** [mfogel/django-timezone-field#75]
It renders as:

```
 timezone:
          enum:
          - !!python/object/apply:pytz._p
            - Africa/Abidjan
            - -960
            - 0
            - LMT
          - !!python/object/apply:pytz._p
            - Africa/Accra
            - -60
            - 0
            - LMT
 ```
etc. Which is not correct. Not sure how to handle this.

**Comment by mfogel** [comment]
Hi @gabn88 

Could you post the commands that you're running to generate that? What is the expected behavior, and what is the behavior that you're seeing? Thanks.

**Comment by mfogel** [comment]
Closed due lack of info on how to reproduce

**Comment by gabn88** [comment]
Sorry for the late reply. /manage.py generateschema --file openapi-schema.yml to create the file.

See https://www.django-rest-framework.org/api-guide/schemas/ for example.
