### ISSUE TITLE
is INSTALLED_APPS needed?

### ISSUE THREAD

**Issue by jmfederico** [mfogel/django-timezone-field#77]
I was wondering why is it important or necessary to add `timezone_field` to `INSTALLED_APPS`?

I cannot see `timezone_field` hooking indo Django in anyway, except by providing tools (fields) that do not really need to exist in an installed app.

Thanks

**Comment by mfogel** [comment]
Thanks for bringing this up @jmfederico ! I've removed references to `INSTALLED_APPS` and everything seems to work fine. This will be included in the next release.
