### ISSUE TITLE
`TimeZoneSerializerField` does not handle the empty string case

### ISSUE THREAD

**Issue by sangiovannidev** [mfogel/django-timezone-field#86]
Hi, thanks for your hard work on django-timezone-field!

`TimeZoneSerializerField.to_internal_value()` seems not to fully handle the empty string ("") case.
With `use_pytz=False`, when the empty string is fed to the the method, it is passed to `ZoneInfo()`, which raises a `ValueError`, as follows:

```python
>>> from zoneinfo import ZoneInfo
>>> ZoneInfo('')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/zoneinfo/_tzpath.py", line 67, in find_tzfile
    _validate_tzfile_path(key)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/zoneinfo/_tzpath.py", line 91, in _validate_tzfile_path
    raise ValueError(
ValueError: ZoneInfo keys must be normalized relative paths, got:
```

I would expect `to_internal_value()` to raise a `ValidationError` instead, which could be handled appropriately by DRF's exception handling machinery.

Please let me know if I can be of further help.

Thanks!

**Comment by ejain** [comment]
Shouldn't empty strings be allowed if the field has `required=False` and `allow_null=True`?

**Comment by mfogel** [comment]
@ejain after #130 is merged, empty strings will be allowed if `allow_blank=True` is specified as [documented by DJRF for their `CharField`](https://www.django-rest-framework.org/community/3.0-announcement/#the-required-allow_null-allow_blank-and-default-arguments)
