### ISSUE TITLE
python3.10 support

### ISSUE THREAD

**Issue by Arthur264** [mfogel/django-timezone-field#89]
please add python3.10 support.

**Comment by mfogel** [comment]
Hi @Arthur264, I think it's already supported
<img width="1312" alt="Screen Shot 2022-09-05 at 16 47 03" src="https://user-images.githubusercontent.com/69902/188521407-e1930712-01eb-445f-8662-896df6b66602.png">

https://github.com/mfogel/django-timezone-field/blob/5.0/pyproject.toml#L39

https://github.com/mfogel/django-timezone-field/blob/5.0/.github/workflows/ci.yml#L55
